export const GET_ALL_CLIENTES = "GET_ALL_CLIENTES";
export const GET_CLIENTE = "GET_CLIENTE";
export const RESET_CLIENTE = "RESET_CLIENTE";
export const BUSCA_CLIENTE_POR_NOMBRE_APELLIDO = "BUSCA_CLIENTE_POR_NOMBRE_APELLIDO";
export const CREA_CLIENTE = "CREA_CLIENTE";
export const MODIFICA_CLIENTE = "MODIFICA_CLIENTE";
export const ELIMINA_CLIENTE = "ELIMINA_CLIENTE";
export const GET_ALL_PRODUCTOS = "GET_ALL_PRODUCTOS";

