export const GET_ALL_CLIENTES = "GET_ALL_CLIENTES";
export const GET_CLIENTE = "GET_CLIENTE";
export const RESET_CLIENTE = "RESET_CLIENTE";
export const BUSCA_CLIENTE_POR_NOMBRE_APELLIDO = "BUSCA_CLIENTE_POR_NOMBRE_APELLIDO";
export const CREA_CLIENTE = "CREA_CLIENTE";
export const MODIFICA_CLIENTE = "MODIFICA_CLIENTE";
export const ELIMINA_CLIENTE = "ELIMINA_CLIENTE";

export const GET_ALL_PRODUCTOS = "GET_ALL_PRODUCTOS";
export const BUSCA_PRODUCTO_POR_NOMBRE = "BUSCA_PRODUCTO_POR_NOMBRE";
export const ELIMINA_PRODUCTO = "ELIMINA_PRODUCTO";

export const GET_ALL_PROVEEDORES = "GET_ALL_PROVEEDORES";
export const CREA_PROVEEDOR = "CREA_PROVEEDOR";
export const BUSCA_PROVEEDOR_POR_NOMBRE_APELLIDO = "BUSCA_PROVEEDOR_POR_NOMBRE_APELLIDO";
export const MODIFICA_PROVEEDOR = "MODIFICA_PROVEEDOR";
export const ELIMINA_PROVEEDOR = "ELIMINA_PROVEEDOR";

